#!/usr/bin/env python3.9
import boto3
import os
ec2 = boto3.resource('ec2')

INSTANCE_TYPE = os.environ['INSTANCE_TYPE']
KEY_NAME = os.environ['KEY_NAME']
AMI=os.environ['AMI']
SUBNET_ID=os.environ['SUBNET_ID']

def lambda_handler(event, context):
    instance = ec2.create_instances(
        InstanceType=INSTANCE_TYPE,
        KeyName=KEY_NAME,
        ImageId=AMI,
        SubnetId=SUBNET_ID,
        MaxCount=1,
        MinCount=1
        Tags=[{'Key':'name', 'Value':'Drytun'}]
    )
    print("New instance created:", instance[0].id)
