#!/user/bin/env python3.9

#project is to create a list of services using Python
services = []

#We will add some 'S3', 'Lambda', 'DynamoDB', 'API Gateway', 'ECS Fargate', 'CloudFormation' to our list
#We use the += so we can add mutiple items at once.
services += ['S3', 'Lambda', 'DynamoDB', 'API Gateway', 'EC2', 'EBS', 'ECS Fargate', 'CloudFormation',]

# lets print the list and the length of the list
list_length = len(services)
length = "Length = "
print(services)
print(length, list_length)

#Lets removed EC2, and EBS from the list since they aint serverless
#We have to reprint it to see the list or we will not get any output
# the [4:6] will delete items 4+5 and not 6 think of it like 4 to 6
del services[4:6]
list_length = len(services)
length = "Length = "
print(services)
print(length, list_length) 


